# Generated by Django 5.2.15 on 2026-06-11 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('n_samples', models.IntegerField(default=3)),
                ('result_s3_key', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('claim_type', models.CharField(max_length=50)),
                ('entities', models.JSONField(default=list)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('source_sentence', models.TextField(blank=True)),
                ('confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('SUPPORTS', 'Supports'), ('CONTRADICTS', 'Contradicts'), ('PARTIAL', 'Partial'), ('NEI', 'Nei')], max_length=20)),
                ('conflict_type', models.CharField(blank=True, choices=[('direct', 'Direct'), ('methodological', 'Methodological'), ('temporal', 'Temporal'), ('population', 'Population')], max_length=20)),
                ('severity', models.IntegerField(null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('source_sentence_a', models.TextField(blank=True)),
                ('source_sentence_b', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='evidence.claim')),
                ('claim_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='evidence.claim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('parsed_sections', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='evidence.analysisjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='evidence.paper'),
        ),
        migrations.CreateModel(
            name='RewardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency_score', models.FloatField(null=True)),
                ('nli_score', models.FloatField(null=True)),
                ('faithfulness_score', models.FloatField(null=True)),
                ('final_confidence', models.FloatField(null=True)),
                ('n_samples', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='evidence.conflictpair')),
            ],
        ),
    ]
