# Generated by Django 5.2.15 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conflictpair',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('causal', 'Causal'), ('comparative', 'Comparative'), ('descriptive', 'Descriptive'), ('factual', 'Factual')], default='factual', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflictpair',
            name='conflict_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('methodological', 'Methodological'), ('temporal', 'Temporal'), ('population', 'Population'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='conflictpair',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardscore',
            name='consistency_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardscore',
            name='faithfulness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardscore',
            name='final_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardscore',
            name='nli_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
