# Generated by Django 5.2.15 on 2026-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_add_claim_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictpair',
            name='error_types',
            field=models.JSONField(default=list, help_text='EvidenceLens error taxonomy: overgeneralization, condition_dropping, false_certainty, missing_evidence, unsupported_claim, wrong_evidence, missing_limitation, contradiction_with_source, conflict_ignored, paper_section_misread'),
        ),
    ]
