# Generated by Django 5.2.15 on 2026-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_answer_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
