# Generated by Django 5.2.15 on 2026-06-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
